name: AdvancedBan
version: ${project.version}
main: ${project.groupId}.bukkit.BukkitMain
author: Leoko
softdepend: [Vault]
api-version: 1.13

commands:
  AdvancedBan:
    description: Information about the Plugin
  fban:
    description: Ban a user permanently
  ftempban:
    description: Ban a user temporarily
  fipban:
    description: Ban a user by IP
    aliases: [banip, ban-ip]
  ftempipban:
    description: Ban a user temporarily by IP
    aliases: [tipban]
  fkick:
    description: Kick a user
  fwarn:
    description: Warn a user permanently
  note:
    description: Adds a note to a users file
  ftempwarn:
    description: Warn a user temporarily
  fmute:
    description: Mute a user permanently
  ftempmute:
    description: Mute a user temporarily
  fbanlist:
    description: See all punishments
  fhistory:
    description: See a user''s history
  fwarns:
    description: See your or a user''s warns
  notes:
    description: See your or a user''s notes
  fcheck:
    description: Get all information about a user
  systemPrefs:
    description: Displays System-Preferences for setting up the plugin
  funwarn:
    description: Deletes a warn
  funnote:
    description: Deletes a note
  funpunish:
    description: Deletes a punishment by ID
  funban:
    description: Unban a user
  funmute:
    description: Unmute a user
  fchange-reason:
    description: Change the reason of an existing punishment